"""Templates for ``atomr-host init`` and ``atomr-host agent new``.

Pulled into a separate module so the CLI stays focused on arg parsing
and so that other tooling (programmatic scaffolds, future ``host
restore`` flow) can reuse the same templates.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from .config import HostConfig, ProviderConfig
from .layout import AgentPaths, HostPaths

try:
    import yaml  # type: ignore[import-untyped]

    _yaml_available = True
except ImportError:  # pragma: no cover
    yaml = None  # type: ignore[assignment]
    _yaml_available = False

__all__ = [
    "default_agent_yaml",
    "scaffold_agent",
    "scaffold_host",
    "seed_agents_md",
]


DEFAULT_CONFIG_YAML = """# atomr-host configuration. Generated by `atomr-host init`.
version: 1
default_agent: default
default_model: gpt-4o
providers:
  openai:
    kind: openai
    api_key_env: OPENAI_API_KEY
  anthropic:
    kind: anthropic
    api_key_env: ANTHROPIC_API_KEY
"""


AGENTS_MD_TEMPLATE = """# AGENTS.md

Routing rules for inbound channel messages → agents.

This file is consumed by M7 (multi-channel gateway). Until then the
host falls back to `default_agent` from `config.yaml`.

## Defaults

- Any unmatched message: default
"""


SOUL_TEMPLATE = """---
identity: A helpful general-purpose assistant.
style:
  tone: warm
  register: friendly
  verbosity: 2
traits:
  - label: helpful
    weight: 0.9
    description: Prioritize concrete, actionable answers.
  - label: concise
    weight: 0.7
    description: Prefer brevity over verbosity; ask before expanding.
---

# Soul

I am the default agent for this atomr-host. I help the user with whatever
they need, drawing on the skills, memory, and tools wired up in
`agent.yaml`.
"""


RULES_TEMPLATE = """# Rules

Behavioral rules. Each non-empty bullet is composed into the agent's
instruction prefix.

- Always acknowledge the user's request before acting on it.
- Prefer asking one clarifying question over guessing.
- If a tool fails, surface the failure rather than retrying silently.
"""


MEMORY_TEMPLATE = """# Memory

Auto-curated facts. Human-editable. Each bullet is one durable fact.

- The user's preferred working hours are 9am–6pm.
"""


USER_TEMPLATE = """# User profile

Inferred-and-edited information about the human on the other side of
the conversation.

- Name: (unknown)
- Communication style: (to be observed)
"""


def default_agent_yaml(agent_id: str, *, model: str = "gpt-4o") -> dict[str, Any]:
    """Return the dict that becomes ``agent.yaml``."""
    return {
        "id": agent_id,
        "model": model,
        "max_iterations": 8,
        "token_budget": 8000,
        "time_budget_ms": 60_000,
        "money_budget_usd": 1.0,
        "skillset_id": f"{agent_id}-skills",
        "skillset_version": "0.1.0",
        # The curation block is consumed by M9. It's emitted here as a
        # documentation aid so users see the strategy point.
        "curation": {
            "strategy": "auto_promote",
            "params": {"min_success_rate": 0.8, "history_limit": 20},
        },
    }


def scaffold_host(root: Path, *, force: bool = False) -> HostConfig:
    """Create the host root skeleton + ``config.yaml`` + ``AGENTS.md``.

    Idempotent: an existing root is left alone. With ``force=True`` an
    existing ``config.yaml`` is overwritten with the template.
    """
    paths = HostPaths(root=root)
    paths.ensure()

    if force or not paths.agents_md.is_file():
        paths.agents_md.write_text(AGENTS_MD_TEMPLATE, encoding="utf-8")

    if force or not paths.config_yaml.is_file():
        paths.config_yaml.write_text(DEFAULT_CONFIG_YAML, encoding="utf-8")

    cfg = HostConfig(
        paths=paths,
        version=1,
        default_agent="default",
        default_model="gpt-4o",
        providers={
            "openai": ProviderConfig(name="openai", kind="openai", api_key_env="OPENAI_API_KEY"),
            "anthropic": ProviderConfig(
                name="anthropic", kind="anthropic", api_key_env="ANTHROPIC_API_KEY"
            ),
        },
    )
    return cfg


def scaffold_agent(
    config: HostConfig,
    agent_id: str,
    *,
    model: str | None = None,
    force: bool = False,
) -> AgentPaths:
    """Create the agent directory skeleton.

    Returns the agent's :class:`AgentPaths`. Idempotent unless ``force``.
    """
    if not _yaml_available:
        raise RuntimeError(
            "PyYAML is required to scaffold an agent — install atomr-agents[host]"
        )
    paths = config.paths.agent(agent_id)
    paths.ensure()
    resolved_model = model or config.default_model or "gpt-4o"

    files: list[tuple[Path, str]] = [
        (paths.agent_yaml, yaml.safe_dump(default_agent_yaml(agent_id, model=resolved_model), sort_keys=False)),
        (paths.soul_md, SOUL_TEMPLATE),
        (paths.rules_md, RULES_TEMPLATE),
        (paths.memory_md, MEMORY_TEMPLATE),
        (paths.user_md, USER_TEMPLATE),
    ]
    for fp, body in files:
        if force or not fp.is_file():
            fp.write_text(body, encoding="utf-8")
    return paths


def seed_agents_md(config: HostConfig) -> None:
    """Re-create ``AGENTS.md`` from the template (used by ``init --force``)."""
    config.paths.agents_md.write_text(AGENTS_MD_TEMPLATE, encoding="utf-8")
